// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
///


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP_T3Idb1rjfwyKzoKpL6vVtA4FHAmAZM',
    appId: '1:687031604465:web:7009388cc0b1fe1c138550',
    messagingSenderId: '687031604465',
    projectId: 'yogau-dd011',
    authDomain: 'yogau-dd011.firebaseapp.com',
    databaseURL: 'https://yogau-dd011-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yogau-dd011.firebasestorage.app',
    measurementId: 'G-5JMZCGRE14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM_OA5-Rgl457MeFoiWmDaAItC38DF6kA',
    appId: '1:687031604465:android:a5018debe196407a138550',
    messagingSenderId: '687031604465',
    projectId: 'yogau-dd011',
    databaseURL: 'https://yogau-dd011-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yogau-dd011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlMTQi7_8XXUvFAqK9cUI6XWnBWraYTRs',
    appId: '1:687031604465:ios:f1cf9ec9bebdf989138550',
    messagingSenderId: '687031604465',
    projectId: 'yogau-dd011',
    databaseURL: 'https://yogau-dd011-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yogau-dd011.firebasestorage.app',
    iosBundleId: 'com.example.yogaCenterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlMTQi7_8XXUvFAqK9cUI6XWnBWraYTRs',
    appId: '1:687031604465:ios:f1cf9ec9bebdf989138550',
    messagingSenderId: '687031604465',
    projectId: 'yogau-dd011',
    databaseURL: 'https://yogau-dd011-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yogau-dd011.firebasestorage.app',
    iosBundleId: 'com.example.yogaCenterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP_T3Idb1rjfwyKzoKpL6vVtA4FHAmAZM',
    appId: '1:687031604465:web:171969b0faaf3d99138550',
    messagingSenderId: '687031604465',
    projectId: 'yogau-dd011',
    authDomain: 'yogau-dd011.firebaseapp.com',
    databaseURL: 'https://yogau-dd011-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yogau-dd011.firebasestorage.app',
    measurementId: 'G-RJ18LH8YB4',
  );
}
